---
- name: Basic Network Setup
  hosts: all
  gather_facts: no
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"
    - name: Set Strong, complex local passwords
      ios_config:
        lines:
          - username admin privilege 15 secret admin
    - name: Configure SSH and disable Telnet
      ios_config:
        lines:
          - ip ssh version 2
          - line vty 0 15
          - transport input ssh
          - transport output ssh
    - name: Configure VTY access limitations
      ios_config:
        lines:
          - line vty 0 15
          - logging synchronous
          - access-class 23 in
          - transport input ssh
          - exec-timeout 30 0
          - login local
    - name: Configure logging and timestamps
      ios_config:
        lines:
          - service timestamps debug datetime msec
          - service timestamps log datetime msec
    - name: Create VLANs for network segmentation
      ios_config:
        lines:
          - interface FastEthernet0/0.10
          - encapsulation dot1Q 10
          - interface FastEthernet0/0.20
          - encapsulation dot1Q 20
          - interface FastEthernet0/0.30
          - encapsulation dot1Q 30
