---
- name: Jinja2 Templates
  hosts: all
  gather_facts: no

  tasks:
    - name: Basic Network Setup
      template:
        src: network_config/templates/basic_network.j2
        dest: "{{ inventory_hostname }}_config.txt"
    - name: Set OSPF
      template:
        src: network_config/templates/routing_setup.j2
        dest: "{{ inventory_hostname }}_ospf.txt"
