---
- name: Jinja2 Templates
  hosts: all
  gather_facts: no

  tasks:
    - name: Basic Network Setup
      template:
        src: basic_network.j2
        dest: "{{ inventory_hostname }}_config.txt"
    - name: Set OSPF
      template:
        src: routing_setup.j2
        dest: "{{ inventory_hostname }}_ospf.txt"
