name: Ansible Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install ansible

      - name: Run Basic Network Setup
        run: ansible-playbook -i network_config/vars/inventory basic_network_setup.yml
     
      - name: Run Routing Protocol setup
        run: ansible-playbook -i network_config/vars/inventory routing_protocol_setup.yml
